version: "3.9"
services:
    express:
        container_name: "express-container"
        build: .
        volumes: 
            - .:/usr/src/app
            - ./node_modules:/usr/src/app/node_modules
        image: "krit/express:1.0.0"
        networks:
            - sub-etha
        ports:
            - "8080:8080"
    mongo:
        container_name: "mongo-container"
        image: "mongo"
        networks:
            - sub-etha
networks:
  sub-etha: